<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>sh</string>
		<string>bash</string>
		<string>zsh</string>
		<string>bashrc</string>
		<string>bash_profile</string>
		<string>bash_login</string>
		<string>profile</string>
		<string>bash_logout</string>
		<string>.textmate_init</string>
		<string>ebuild</string>
	</array>
	<key>firstLineMatch</key>
	<string>^#!.*\b(bash|zsh|sh|tcsh)|^#\s*-\*-[^*]*mode:\s*shell-script[^*]*-\*-</string>
	<key>foldingStartMarker</key>
	<string>\b(if|case)\b|(\{|\b(do)\b)$</string>
	<key>foldingStopMarker</key>
	<string>^\s*(\}|(done|fi|esac)\b)</string>
	<key>keyEquivalent</key>
	<string>^~S</string>
	<key>name</key>
	<string>Shell Script (Roundup)</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>source.ruby</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.shell.roundup</string>
	<key>uuid</key>
	<string>3C6B309B-3BA2-4213-83F5-04B484B6229C</string>
</dict>
</plist>
